version: "3.9"

services:
  mongo_db:
    container_name: crudAPI_db
    image: mongo:latest
    restart: always
    volumes:
      - "mongo_db:/data/db"
  
  api:
    build: ./
    ports:
      - "3000:3000"
  
    environment:
      PORT: 3000:3000
      MONGODB_URI: mongodb://crudAPI_db:27017
      DB_NAME: crud_mongodb
      NAME: shubham
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}